Repository snapshot-labs/snapshot.js, pull requests merged in 2021-07, with the labels that each got.

#280 refactor(package): specify Node dependency fixes #279
  package.json
Labels: bug

#285 [aavegotchi-agip] Add strategy for aavegotchi agip 8+9
  src/strategies/aavegotchi-agip/examples.json
  src/strategies/aavegotchi-agip/index.ts
  src/strategies/index.ts
Labels: strategy

#284 [planet-finance] Add Strategy
  src/strategies/index.ts
  src/strategies/planet-finance/examples.json
  src/strategies/planet-finance/index.ts
Labels: strategy

#283 Update README for development Instructions
  README.md
Labels: documentation

#282 [erc20-balance-of-quadratic-delegation] A new strategy for quadratic delegations
  src/strategies/erc20-balance-of-quadratic-delegation/README.md
  src/strategies/erc20-balance-of-quadratic-delegation/examples.json
  src/strategies/erc20-balance-of-quadratic-delegation/index.ts
  src/strategies/index.ts
Labels: strategy

#290 [eth-with-balance] Add eth-with-balance strategy
  src/strategies/eth-balance/examples.json
  src/strategies/eth-with-balance/README.md
  src/strategies/eth-with-balance/examples.json
  src/strategies/eth-with-balance/index.ts
  src/strategies/index.ts
Labels: strategy

#291 [impossible-finance] Impossible strategy
  src/strategies/impossible-finance/README.md
  src/strategies/impossible-finance/examples.json
  src/strategies/impossible-finance/index.ts
  src/strategies/index.ts
Labels: strategy

#293 [impossible-finance] Impossible strategy
  src/strategies/impossible-finance/examples.json
  src/strategies/impossible-finance/index.ts
Labels: strategy

#288 [modefi-staking] Add Strategies - Modefi
  src/strategies/index.ts
  src/strategies/modefi-staking/examples.json
  src/strategies/modefi-staking/index.ts
Labels: strategy

#292 [ruler-staked-token] Add ruler-staked-token strategy
  src/strategies/index.ts
  src/strategies/ruler-staked-token/README.md
  src/strategies/ruler-staked-token/examples.json
  src/strategies/ruler-staked-token/index.ts
Labels: strategy

#303 [balancer-smart-pool] Add/balancer smart pool token score
  src/strategies/balancer-smart-pool/examples.json
  src/strategies/balancer-smart-pool/index.ts
  src/strategies/index.ts
Labels: strategy

#299 [badgeth] Badgeth strategy
  src/strategies/badgeth/examples.json
  src/strategies/badgeth/index.ts
  src/strategies/index.ts
Labels: strategy

#296 [tranche-staking-slice] Tranche Staked SLICE strategy
  src/strategies/index.ts
  src/strategies/tranche-staking-slice/examples.json
  src/strategies/tranche-staking-slice/index.ts
Labels: strategy

#310 [unipool-same-token] Add unipool-same-token strategy
  src/strategies/index.ts
  src/strategies/unipool-same-token/examples.json
  src/strategies/unipool-same-token/index.ts
Labels: strategy

#311 [balancer-smart-pool] update balancer-smart-pool strategy to compare weights to total supply
  src/strategies/balancer-smart-pool/index.ts
Labels: strategy

#314 [planet-finance] New Voting Strategy
  src/strategies/planet-finance/examples.json
  src/strategies/planet-finance/index.ts
Labels: strategy

#309 [zrx-voting-power] ZRX voting power strategy
  src/strategies/index.ts
  src/strategies/zrx-voting-power/README.md
  src/strategies/zrx-voting-power/examples.json
  src/strategies/zrx-voting-power/index.ts
Labels: strategy

#322 [ogn] Add new ogn strategy
  src/strategies/index.ts
  src/strategies/ogn/README.md
  src/strategies/ogn/examples.json
  src/strategies/ogn/index.ts
Labels: strategy

#319 [tomb-finance] New strategy for tomb.finance
  src/strategies/index.ts
  src/strategies/tomb-finance/examples.json
  src/strategies/tomb-finance/index.ts
Labels: strategy

#315 [unipool-univ2-lp] Add unipool-univ2-lp strategy
  src/strategies/index.ts
  src/strategies/unipool-univ2-lp/examples.json
  src/strategies/unipool-univ2-lp/index.ts
Labels: strategy

#323 [aavegotchi] update strategy to add ghstweth pool power
  src/strategies/aavegotchi/examples.json
  src/strategies/aavegotchi/index.ts
Labels: strategy

#326 [zrx-voting-power] Hotfix for zrx-voting-power strategy
  src/strategies/zrx-voting-power/examples.json
  src/strategies/zrx-voting-power/index.ts
Labels: strategy

#321 [masterchef-pool-balance-price] Add strategy to get the balance or price of any combination of tokens for a pool using a masterchef contract.
  src/strategies/index.ts
  src/strategies/masterchef-pool-balance-price/README.md
  src/strategies/masterchef-pool-balance-price/examples.json
  src/strategies/masterchef-pool-balance-price/index.ts
Labels: strategy

#327 [tomb-finance] Fix tomb-finance strategy precision
  src/strategies/tomb-finance/index.ts
Labels: strategy

#333 [decentraland-estate-size] Fix decentraland-estate-size block issue
  src/strategies/decentraland-estate-size/index.ts
Labels: strategy

#331 [balance-of-with-thresholds] Add balance-of-with-thresholds strategy
  src/strategies/balance-of-with-thresholds/README.md
  src/strategies/balance-of-with-thresholds/examples.json
  src/strategies/balance-of-with-thresholds/index.ts
  src/strategies/index.ts
Labels: strategy

#342 [erc721-with-tokenid] Add ERC721 with tokenid strategy
  src/strategies/erc721-with-tokenid/README.md
  src/strategies/erc721-with-tokenid/examples.json
  src/strategies/erc721-with-tokenid/index.ts
  src/strategies/index.ts
Labels: strategy
